### ISSUE TITLE
test.html是最后的网页吗？下载下来点开只有文字，css和js都挂了

### ISSUE THREAD

**Issue by stillsilly** [xdsnet/sTw#1]

**Comment by xdsnet** [comment]
不光是test.html文件，还需要css、js，以及xml文件，你最好全部下载所有文件。并认真阅读readme.md文件中的说明进行操作。
我刚才也在Firefox43.0.4上再次验证了项目是可用的。
如果有问题，请给出详细的信息，包括运行环境。
一点需要注意的是因为浏览器开发中对安全问题处理机制的限制，有些浏览器（例如Chrome）不能在本地加载xml文件，可能致页面不能打开（如果打开调试，应该能看到相应的报错），对于这样的浏览器访问测试，要么在本地搭建HTTP服务，要么把资源放置到远端HTTP服务器上进行访问测试。

**Comment by stillsilly** [comment]
嗯，试了下火狐，可以打开了，之前用的Chrome。thx(๑• . •๑)
